### PR TITLE
Filter on type and method attributes to skip F# implementation details

### PR DESCRIPTION
**Pull request by SteveGilham**
-- this was done with F# 4.1; there may be slight differences at earlier versions
  -- it is all implementation detail anyway, so not documented
  -- unit tests include the F# source used and the built assembly
  -- no need for F# to be installed to build or to be included in the installer

### The issue or feature being addressed

#615

### Details on the issue fix or feature implementation

By examining how the compiler-generated methods on an F# structure or discriminated union are represented, provide a heuristic to detect them and mark them as skipped.

Now running ReportGenerator over coverage gathered an NUnit 2.6.4 test of the included Library1.dll, the type declarations themselves appear in white, whereas user defined code gets appropriate colouration.

### Confirm the following

- [X] I have ensured that I have merged the latest changes from the main branch (or whichever branch is appropriate) from opencover/opencover
- [X] I have run `build create-release` locally and have encountered no issues
- [X] I agree to follow up on any work required to resolve any issues identified whilst my request is being accepted

---
This change is [Reviewable](https://reviewable.io/reviews/opencover/opencover/758)

### CODE REVIEW

**Comment by SteveGilham** [comment]
Doesn't quite work with VS2010 (first release with F# included) -- as I'd feared, there are changes in the implementation details.  

Update in progress.

**Comment by SteveGilham** [comment]
Having built the appropriate branch, and used VS2010 (the first full F# release) to build the same debug test assembly, the automatic parts are hidden as expected, which allays my fears about the internal implementation details changing.  There were significant changes in implementation details in earlier versions as I blogged back at the time, but I would hope that nobody is still using those, and they can be left unsupported.

Built in release, however, both F#2.0 and F#4.1 now show user written code as not covered (while still correctly hiding the automatic parts).

I'm investigating.

**Comment by SteveGilham** [comment]
> so I'll raise a separate issue for this.
That was issue #760, and on further examination, it is not fixable.

**Comment by sawilde** [comment]
@SteveGilham do we still need this PR as #760 was closed?

**Comment by SteveGilham** [comment]
This PR addresses the original issue #615 for the case when we don't have code inlining involved, by exempting from the tally the compiler generated methods that are associated with F# structure and discriminated union types, just as is done for automatic properties in C#.  

So yes, I'd say it should still stand -- as an analogu if, for example, I could concoct a C# example containing automatic properties that had some in-lining in release builds, we'd still want to keep exempting auto-properties.

**Pull request merged**
