### PR TITLE
Update to Mono.Cecil 0.10.0 release package

### PR DESCRIPTION
**Pull request by tmat**
### The issue or feature being addressed

https://github.com/OpenCover/opencover/issues/610

### Details on the issue fix or feature implementation

Updates to the release version of Mono.Cecil 0.10.0 package.

### Confirm the following

- [ ] I have ensured that I have merged the latest changes from the main branch (or whichever branch is appropriate) from opencover/opencover
- [ ] I have run `build create-release` locally and have encountered no issues
- [ ] I agree to follow up on any work required to resolve any issues identified whilst my request is being accepted

---
This change is [Reviewable](https://reviewable.io/reviews/opencover/opencover/814)

### CODE REVIEW

**Comment by kasper3** [comment]
@sawilde, can this be merged please?
@tmat, seems like CLA is not signed. :)

**Comment by tmat** [comment]
@kasper3 Signed now.

**Comment by jnm2** [comment]
In the meantime, a non-prerelease of 0.10.0 has been published.

**Comment by sharwell** [comment]
@jnm2 Yes, this pull request updates the project to the release you mention.

**Comment by jnm2** [comment]
Dear me, I misread the diff. Sorry!

**Comment by pjanotti** [comment]
I validated this PR against CoreFX repo and it works fine for Portable PDBs, however, Mono.Cecil is failing for WindowsPDB from CoreFx repo - I will follow up on that.

**Comment by ViktorHofer** [comment]
Kindly asking, what's the status here @sawilde? Not merging this currently blocks us in .NET Core repositories (corefx, coreclr, wcf). We are already looking for alternatives...

**Comment by sharwell** [comment]
@sawilde Is there something blocking this pull request that we can assist with?

**Comment by jkoritzinsky** [comment]
@sawilde there's a Mono.Cecil 0.10.1 release out now. Can this get merged in soon?

**Pull request merged**
