### PR TITLE
Removing duplicate modules (by hash) if -mergebyhash is set

### PR DESCRIPTION
**Pull request by squid-box**
### The issue or feature being addressed

Attempts to fix the issue reported in #908 (Intermittent duplicate Modules in XML report)

### Details on the issue fix or feature implementation

This fix is more a band-aid on the symptom, rather than a fix for the root cause. I've tried to track down why I sometimes end up with duplicate modules even with `-mergebyhash` set, but haven't been able to.

This will remove any duplicate (by hash) modules, if `-mergebyhash` is set, before scores etc. are calculated.

I'm open to suggestions on how to better fix/suppress my issue.

### Confirm the following

- [X] I have ensured that I have merged the latest changes from the main branch (or whichever branch is appropriate) from opencover/opencover
- [x] I have run `build create-release` locally and have encountered no issues
- [X] I agree to follow up on any work required to resolve any issues identified whilst my request is being accepted 
- [X] I have tagged my commits using the issue number syntax #nnn 

I'm having issues getting the .NET Core 2.0 projects building, hoping that AppVeyor will prove the `build create-release` step for me. Otherwise just ignore the PR until I've managed to get a full local build done.

---
This change is [Reviewable](https://reviewable.io/reviews/opencover/opencover/909)

### CODE REVIEW

**Comment by squid-box** [comment]
Building locally I have 4 failures under `test-bdd`:
* OpenCover.Specs.DotNetCoreFeature.GetCoverageOfA_NetCore1_1Application
* OpenCover.Specs.DotNetCoreFeature.GetCoverageOfA_NetCore1_1ApplicationWithDebugTypeEmbedded
* OpenCover.Specs.DotNetCoreFeature.GetCoverageOfA_NetCore1_1ApplicationWithDebugTypePortable
* OpenCover.Specs.DotNetCoreFeature.GetCoverageOfA_NetCoreApplicationUsingOldstyle

Building on AppVeyor I have 3 failures under `test-bdd`:
* OpenCover.Specs.PackagingFeature.RunOpenCoverAfterInstallingFromANugetPackage
* OpenCover.Specs.PackagingFeature.RunOpenCoverAfterInstallingFromAnInstaller
* OpenCover.Specs.PackagingFeature.RunOpenCoverAfterInstallingFromZipFile

The 4 local failures work on AppVeyor, and the 3 AppVeyor failures work locally. I have no idea what's going on here.

**Comment by squid-box** [comment]
@sawilde: Actually after creating my own AppVeyor project (of OpenCover) to troubleshoot - it looks like the current OpenCover master [67980c8132b1d574beb1feaa7d269c9dca47b812] is failing those tests.

**Comment by sawilde** [comment]
That is odd as the current master https://ci.appveyor.com/project/sawilde/opencover is showing it as AOK - I'll see if I can find time to investigate in the next few days

**Comment by squid-box** [comment]
Yeah, I would assume something has changed in AppVeyor's image sometime during the past 4 months, since the code remains unchanged (and that the failing tests work locally for me).

[Here's a link to my failing build of OpenCover master](https://ci.appveyor.com/project/squid-box/opencover/builds/26632415)

**Comment by squid-box** [comment]
@sawilde: "A while" later, with the build issue fixed - the checks are good, just the question of if my solution is :)

I still feel this is a "fix" that cleans up the symptoms of some other problem, but the inconsistent nature of #908 has made it hard to find the source of the problem.

If you don't approve of it, it's fine to close - we have been using a private branch with this fix for our needs with good results so far.

**Comment by sawilde** [comment]
There could be coverage recorded in one module that isn't in the others and so is lost during the removal of other modules that match the hash

**Comment by carlos-quintero** [comment]
This is a bad way of fixing the symptom and not the cause. I was able to reproduce the problem and find the root cause through debugging. See: https://github.com/OpenCover/opencover/issues/908#issuecomment-725292541

**Comment by squid-box** [comment]
@carlos-quintero : Yep, I should've closed this PR a long while back. Good to hear you've managed to track down the cause!

**Pull request closed without merging**
