### PR TITLE
Coverity: resource leak on exceptional cases

### PR DESCRIPTION
**Pull request by molnargab**
Coverity issues 134126, 134127, 134128

#417

### CODE REVIEW

**Comment by ddur** [comment]
Sorry, this is done yesterday. Nothing left today.
Before taking issue, check action field, if is "Fix Required", change to "Fix Submitted"

**Comment by sawilde** [comment]
@ddur I think @molnargab sort of did the same thing as you but turned your code into a `using` statement. I agree however that in future we need to check the tickets beforehand and perhaps use the assigned field when we decide to take on an issue to fix.

**Comment by ddur** [comment]
@sawilde 
Yes @molnargab did well but too late. 

Anyway, this merge has conflicts.

**Comment by molnargab** [comment]
@ddur, I still saw those issues unresolved on Coverity, and checking the code those resources were indeed not disposed, in case of an Exception occured, before calling `Close` or `Dispose`.

But if you say it's the same, I may have seen some stale report though :)

**Comment by ddur** [comment]
@molnargab 
Sorry, I will leave all future Coverity issues to you.

BTW, googleDns has no IDisposable interface, that's why I used .Close method instead of using.

**Comment by sawilde** [comment]
I think we should use the assigned filed if we decide to take on a new reported defect and create a ticket on github (if appropriate) and tag it coverity. The assigned filed does work but it is a slow; spinning wait cursor.

**Comment by ddur** [comment]
In "Triage History" one can see all changes by user.

**Pull request closed without merging**
