### PR TITLE
Sync CorClr_Profiler_Path with Cor_Profiler_Path

### PR DESCRIPTION
**Pull request by istanishev**

### CODE REVIEW

**Comment by sawilde** [comment]
I didn't even know there was a CorClr_Profiler_Path - I wonder when that got added?

I also see there are some 32/64 bit variations in the pipeline

https://github.com/DickvdBrink/coreclr/commit/a57827d1684cc67390bd44242b8c73c856424b2f

**Comment by istanishev** [comment]
This is what I found: http://blogs.msdn.com/b/davbr/archive/2010/01/21/writing-a-profiler-for-silverlight-4.aspx

I'm having an issue where OpenCover/.Net is loading both the profiler specified in x_PATH variable as well as the one defined in windows registry. I see only Cor_Prolifer_Path set to point the the dll and CorClr_Profiler pointing to the dll specified in windows registry.

**Comment by sawilde** [comment]
Odd - I would say if you are using COR(CLR)_PROFILER_PATH then don't register the COM object - the runtime loads the profiler the cnsole app just provides the information to the runtime (via env vars) to find and launch it.

**Comment by istanishev** [comment]
Unfortunately, I dont exactly have control over the registration so in my case I should assume I have the registration already done. But I don't want to use the registered profiler and that's why I'm setting the x_PATH env variable. After running opencover with -register:Path64, I can see that the nunit-console process is opening both profilers. 

When I remove the registry entries for the profiler and pass -register:Path64, it works as expected.

**Comment by sawilde** [comment]
awesome find

**Pull request merged**
