### PR TITLE
Spurious BranchPoints

### PR DESCRIPTION
**Pull request by ddur**
This modification should exclude from reports all "spurious" branch-points as part of existing branch-points processing (loop). Also fixes so far uncovered case when BP offset is lower than first SP start-offset.

I think that IL profiler must be high-language-instruction and compiler-construction unaware&neutral, and profile every IL instruction it is supposed to profile.

Problem with matching BP to SP is that SP has start-line, start-column, end-line, end-column, but only start-offset, no end-offset. BP has only offset info. Compiler can insert arbitrary IL code in space between two SP's.

### CODE REVIEW

**Comment by ddur** [comment]
As far as I understand, failed test `BasePersistenceTests.cs` tries to persist BranchPoint only, but with this pull request, no BranchPoint will persist without matching SequencePoint.

**Comment by ddur** [comment]
Test failed because there is a difference between coverage result for 32/64 platform on install packages. 
It would be great if someone could provide me test coverage result for x64 platform (or both).

**Comment by ddur** [comment]
I guess, this will wait until I install 64bit windows.

**Comment by ddur** [comment]
@sawilde, please review if this commit https://github.com/ddur/opencover/commit/ccc977765484e3d2ed1ad907c6118c6c0c4074cc is ok.

**Comment by sawilde** [comment]
Thanks, due to other events I am not active on the project at the moment - I'll hopefully get back to this project before xmas

**Pull request closed without merging**
